name: Github Actions Template

on: push
 
jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    environment: staging
    env:
      SPN_ID: ${{ secrets.SPN_ID }}
      SPN_PASS: ${{ secrets.SPN_PASS }}
    steps:
    - name: Connecting to Azure
      run: |
        echo $SPN_PASS
    - name: Azure Login
      uses: Azure/login@v1.4.5
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Run az commands'
      run: |
        az account show
        az group list
        pwd 
  
  
